version: 2
workflows:
  version: 2
  build:
    jobs:
      # - build-vol1:
      #     context: z7-stage
      - build-vol2:
          context: z7-stage
      # - build-vol1-final:
      #     context: z7-stage
      # - build-vol1-instructors:
      #     context: z7-stage
      # - build-vol1-fast:
      #     context: z7-stage
      - docs-deploy:
          requires:
            # - build-vol1
            - build-vol2
            # - build-vol1-final
            # - build-vol1-instructors
            # - build-vol1-fast
          # filters:
          #   branches:
          #     only: publish
jobs:
  build-vol1:
    docker:
      - image: ${DOCKER_REGISTRY}/act4e/act4e-build:z7
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - store_artifacts:
          path: build-stats
          destination: build-stats
      - run:
          name: instructors
          command: |
            git clone -b spring2021 git@github.com:ACT4E/ACT4E-solutions.git

      - run:
          name: Latex
          command: |
            mkdir _build
            make nomenc
            make table
            make ACT4E-vol1.pdf
            cp *log *warnings.txt _build
      - run:
          name: encrypt
          command: |
            pdftk ACT4E-vol1.pdf output _build/ACT4E-vol1.pdf owner_pw ${OWNER_PWD} user_pw ${USER_PWD}
      - store_artifacts:
          path: _build
          destination: _build
      - persist_to_workspace:
          root: .
          paths:
            - _build
  build-vol2:
    docker:
      - image: ${DOCKER_REGISTRY}/act4e/act4e-build:z7
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - store_artifacts:
          path: build-stats
          destination: build-stats
      - run:
          name: instructors
          command: |
            git clone -b spring2021 git@github.com:ACT4E/ACT4E-solutions.git

      - run:
          name: Latex
          command: |
            mkdir _build
            make nomenc
            make table
            make ACT4E-vol2.pdf
            cp *log *warnings.txt _build
      - run:
          name: encrypt
          command: |
            pdftk ACT4E-vol2.pdf output _build/ACT4E-vol1.pdf owner_pw ${OWNER_PWD} user_pw ${USER_PWD}
      - store_artifacts:
          path: _build
          destination: _build
      - persist_to_workspace:
          root: .
          paths:
            - _build
  build-vol1-fast:
    docker:
      - image: ${DOCKER_REGISTRY}/act4e/act4e-build:z7
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run:
          name: instructors
          command: |
            git clone -b spring2021 git@github.com:ACT4E/ACT4E-solutions.git


      - run:
          name: Latex
          command: |
            mkdir _build
            make nomenc
            make table
            make ACT4E-vol1-fast.pdf
            cp *log *warnings.txt _build
      - run:
          name: encrypt
          command: |
            pdftk ACT4E-vol1-fast.pdf output _build/ACT4E-vol1-fast.pdf owner_pw ${OWNER_PWD} user_pw ${USER_PWD}

      - store_artifacts:
          path: _build
          destination: _build
      - persist_to_workspace:
          root: .
          paths:
            - _build

  build-vol1-instructors:
    docker:
      - image: ${DOCKER_REGISTRY}/act4e/act4e-build:z7
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run:
          name: instructors
          command: |
            git clone -b spring2021 git@github.com:ACT4E/ACT4E-solutions.git

      - run:
          name: Latex
          command: |
            mkdir _build
            make nomenc
            make table
            make ACT4E-vol1-instructors.pdf
            cp *log *warnings.txt _build
      - run:
          name: encrypt
          command: |
            pdftk ACT4E-vol1-instructors.pdf output _build/ACT4E-vol1-instructors.pdf owner_pw ${OWNER_PWD} user_pw ${USER_PWD}
      - store_artifacts:
          path: _build
          destination: _build
      - persist_to_workspace:
          root: .
          paths:
            - _build

  build-vol1-final:
    docker:
      - image: ${DOCKER_REGISTRY}/act4e/act4e-build:z7
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run:
          name: Latex
          command: |
            mkdir _build
            make nomenc
            make table
            make ACT4E-vol1-final.pdf
            cp ACT4E-vol1-final.pdf _build
            cp *log *warnings.txt _build

      - store_artifacts:
          path: _build
          destination: _build
      - persist_to_workspace:
          root: .
          paths:
            - _build

  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: tmp/workspace
      - run:
          name: Config git
          command: |
            git config --global user.email "acensi@ethz.ch"
            git config --global user.name "ci-build"
      
      - run:
          name: install git lfs
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
            apt-get install git-lfs -y
            git lfs install
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --unsafe-perm=true netlify-cli
      
      - run:
          name: netlify
          command: |
            netlify login
            netlify status

      - run:
          name: install lm
          command: |
            netlify lm:install
            netlify lm:info

      - run:
          name: Deploy docs to gh-pages branch
          command: |
            GIT_LFS_SKIP_SMUDGE=1 git clone --depth 1 -b master git@github.com:idsc-frazzoli/ACT4E-target.git docs

            cd docs && netlify link --name=act4e-spring21

            cp pages-index.html docs
            cp tmp/workspace/_build/* docs
            git -C docs add .
            git -C docs commit -a -m "update [ci skip]"
            git -C docs push

            cd docs && netlify deploy --dir=. --prod 
